version: "3.9"

services:
  db:
    container_name: db
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}